
project_id = "lskrxwxbmvswrrsnrvux"

[functions.create-admin]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.delete-member]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true
